version: '3.8'

services:
  app:
    build: .
    container_name: aether-cdn
    ports:
      - "4321:4321"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=4321
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: aether-cdn-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/usr/share/nginx/html/uploads
    depends_on:
      - app
    restart: unless-stopped
